version: 0.1

phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt install amazon-ecr-credential-helper
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - mvn install
      # - mvn compile jib:build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - $(aws ecr get-login --no-include-email --region us-east-1)
      - mvn compile jib:build