version: 0.1

phases:
  install:
    commands:
      - echo Entered the install phase...
      # docker-credential-ecr-login required for mvn compile jib:build
      - go get -u github.com/awslabs/amazon-ecr-credential-helper/ecr-login/cli/docker-credential-ecr-login
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - $(aws ecr get-login --no-include-email --region us-east-1)
      - mvn compile jib:build